### ISSUE TITLE
Separate plugin list into types of plugins

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/gui-docs#20]
Or, if this is difficult to do on the menu, have a page listing them by plugin type.
This is helpful to help navigate plugins when you don't know what they do.
Eg: browse the plugin list by "Sink" to understand the different ways in which the acq board can interact with other devices via the GUI.

**Comment by jsiegle** [comment]
Unfortunately we can't group pages within more than two levels and still have all the plugins appear on the sidebar.

But we did just add a list of all plugins of each type to the index page: https://open-ephys.github.io/gui-docs/User-Manual/Plugins/index.html

Let me know if that addresses the issue!

**Comment by ChucklesOnGitHub** [comment]
Looks amazing! Great resource to point new users to, thanks :)
