### ISSUE TITLE
Add data definitions?

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/gui-docs#21]
I couldn't find an explicit definition of data stream, different data types and left to right processing.
I was also looking for a place to include internal lines that are not the more obvious 1-8 on the acq board.
So maybe a section defining how data is handled in general could help?

Maybe a good place for this is in page https://open-ephys.github.io/gui-docs/User-Manual/Exploring-the-user-interface.html
New title "Data processing" right before "Main components" could work.

Something like (please @jsiegle can you check for technical correctness and suitability):

The GUI processes different data types such as continuous signals, events, spikes and messages. 

- Continuous signals: neural channels and auxiliary inputs on a headstage such as an accelerometer, as well as analog inputs acquired from other hardware.
- Events: discrete ‘high’ or ‘low’ signals from TTL lines in hardware or from other plugins that are used to indicate when something occured
- Spikes: used for waveforms, timestamps and cluster ID of spike events that are detected in neural data
- Text events: messages from user input or plugin communications

Data is processed in the signal chain from left to right in what are called "data streams". There can be multiple data streams in parallel. Data streams deal with data from selected sources (for example, a headstage or a file), as well as internal TTL lines. The GUI supports 256 TTL lines internally. A subset of these is accessible by hardware. For example, TTL lines 1-8 can be accesed by connecting an I/O board to the digital input or output of the Open Ephys Acquisition Board.

The last part might be a handful for the first section of the docs, but it also immediately gives you an idea of where data lives in the software and what you are going to be juggling with. I didn't do a pull request so we can discuss.

**Comment by jsiegle** [comment]
These are all great suggestions, I will work on incorporating these!

**Comment by jsiegle** [comment]
Just expanded the [Signal chain](https://open-ephys.github.io/gui-docs/User-Manual/Exploring-the-user-interface.html#signal-chain) section to include this info. Let me know if this looks good, or if there's anything else I should add!
