### ISSUE TITLE
logo font issue

### ISSUE THREAD

**Issue by jonnew** [open-ephys/gui-docs#30]
I think the use of text (instead of primitive shapes) in the logo SVG is causing the font to look inconsistent across browsers/systems. 
Might want to use PNG instead or use font outlines.

![Screenshot from 2023-07-08 08-27-35](https://github.com/open-ephys/gui-docs/assets/1429475/0078298a-5e6c-4a5e-88e1-a7ec4d377c84)

**Comment by jsiegle** [comment]
Fixed with latest commit.

**Comment by jsiegle** [comment]
Will push the same change to the other repos shortly.
