### ISSUE TITLE
Acquisition Board Output plugin doc page?

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/gui-docs#34]
I can't seem to find them and it would be helpful to have the plugin functionality documented

**Comment by jsiegle** [comment]
You're right it doesn't exist yet...I can add it!

**Comment by ChucklesOnGitHub** [comment]
It lives here: https://open-ephys.github.io/gui-docs/User-Manual/Plugins/Acq-Board-Output.html
